// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/client/models/models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemType is a type of an item
type ItemType int32

const (
	ItemType_NONE             ItemType = 0  // ItemType_NONE is used for items without concrete type
	ItemType_LOGIN            ItemType = 1  // ItemType_LOGIN is used for items with login, password
	ItemType_SECURE_KEY       ItemType = 2  // ItemType_SECURE_KEY is used for items with key/password
	ItemType_EMAIL_ACCOUNT    ItemType = 3  // ItemType_EMAIL_ACCOUNT is used for email accounts
	ItemType_BANK_CARD        ItemType = 4  // ItemType_BANK_CARD is used for bank cards
	ItemType_IDENTITY         ItemType = 5  // ItemType_IDENTITY is used for identities like passport or driver license
	ItemType_SECURE_NOTE      ItemType = 6  // ItemType_SECURE_NOTE is used for secure notes
	ItemType_SECURE_FILE      ItemType = 7  // ItemType_SECURE_FILE is used for secure files
	ItemType_SERVER_CREDS     ItemType = 8  // ItemType_SERVER_CREDS is used for server credentials
	ItemType_WIRELESS_ROUTER  ItemType = 9  // ItemType_WIRELESS_ROUTER is used for WiFi router credentials
	ItemType_SOFTWARE_LICENSE ItemType = 10 // ItemType_SOFTWARE_LICENSE is used for software licenses
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0:  "NONE",
		1:  "LOGIN",
		2:  "SECURE_KEY",
		3:  "EMAIL_ACCOUNT",
		4:  "BANK_CARD",
		5:  "IDENTITY",
		6:  "SECURE_NOTE",
		7:  "SECURE_FILE",
		8:  "SERVER_CREDS",
		9:  "WIRELESS_ROUTER",
		10: "SOFTWARE_LICENSE",
	}
	ItemType_value = map[string]int32{
		"NONE":             0,
		"LOGIN":            1,
		"SECURE_KEY":       2,
		"EMAIL_ACCOUNT":    3,
		"BANK_CARD":        4,
		"IDENTITY":         5,
		"SECURE_NOTE":      6,
		"SECURE_FILE":      7,
		"SERVER_CREDS":     8,
		"WIRELESS_ROUTER":  9,
		"SOFTWARE_LICENSE": 10,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_client_models_models_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_internal_client_models_models_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{0}
}

// FieldType is a type of an item field
type FieldType int32

const (
	FieldType_TEXT             FieldType = 0 // FieldType_TEXT is used for single-line text fields
	FieldType_SECRET           FieldType = 1 // FieldType_SECRET is used for secret fields like passwords
	FieldType_NOTE             FieldType = 2 // FieldType_NOTE is used for multi-line text fields
	FieldType_URL              FieldType = 3 // FieldType_URL is used for URL fields
	FieldType_EMAIL            FieldType = 4 // FieldType_EMAIL is used for email fields
	FieldType_PHONE            FieldType = 5 // FieldType_PHONE is used for phone fields
	FieldType_BANK_CARD_NUMBER FieldType = 6 // FieldType_BANK_CARD_NUMBER is used for bank card number fields
	FieldType_DATE             FieldType = 7 // FieldType_DATE is used for date fields
	FieldType_MONTH_YEAR       FieldType = 8 // FieldType_MONTH_YEAR is used for month/year fields
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "TEXT",
		1: "SECRET",
		2: "NOTE",
		3: "URL",
		4: "EMAIL",
		5: "PHONE",
		6: "BANK_CARD_NUMBER",
		7: "DATE",
		8: "MONTH_YEAR",
	}
	FieldType_value = map[string]int32{
		"TEXT":             0,
		"SECRET":           1,
		"NOTE":             2,
		"URL":              3,
		"EMAIL":            4,
		"PHONE":            5,
		"BANK_CARD_NUMBER": 6,
		"DATE":             7,
		"MONTH_YEAR":       8,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_client_models_models_proto_enumTypes[1].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_internal_client_models_models_proto_enumTypes[1]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{1}
}

// ItemMeta is a metadata of an item.
// Contains no sensitive data like passwords and keys.
type ItemMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // Id is an ID of an item
	CreatedAt   int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // CreatedAt is a timestamp of item creation
	UpdatedAt   int64    `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // UpdatedAt is a timestamp of item update
	Title       string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                           // Title is a title of an item
	Type        ItemType `protobuf:"varint,5,opt,name=type,proto3,enum=models.ItemType" json:"type,omitempty"`       // Type is a type of an item
	Deleted     bool     `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`                      // Deleted is true if item is deleted
	Attachments [][]byte `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`               // Attachments contains IDs of item attachments
}

func (x *ItemMeta) Reset() {
	*x = ItemMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_models_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMeta) ProtoMessage() {}

func (x *ItemMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_models_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMeta.ProtoReflect.Descriptor instead.
func (*ItemMeta) Descriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *ItemMeta) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ItemMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ItemMeta) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ItemMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItemMeta) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_NONE
}

func (x *ItemMeta) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *ItemMeta) GetAttachments() [][]byte {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// ItemData is a data of an item. Contains sensitive data like passwords and keys.
type ItemData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"` // Fields is a list of item fields
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_models_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_models_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{1}
}

func (x *ItemData) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Field is a field of an item
type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order uint32    `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`                     // Order is a field order on the screen form
	Title string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                      // Title is a title of a field
	Type  FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=models.FieldType" json:"type,omitempty"` // Type is a type of a field
	Value []byte    `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                      // Value is a value of a field
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_models_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_models_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Field) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Field) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_TEXT
}

func (x *Field) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// AttachmentMeta is a metadata of an attachment.
// Contains no sensitive data.
type AttachmentMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // Id is an ID of an attachment
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // CreatedAt is a timestamp of attachment creation
	UpdatedAt int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // UpdatedAt is a timestamp of attachment update
	FileName  string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`     // FileName is a file name of an attachment
	FileSize  uint64 `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // FileSize is a file size of an attachment
	Deleted   bool   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`                      // Deleted is true if attachment is deleted
}

func (x *AttachmentMeta) Reset() {
	*x = AttachmentMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_models_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentMeta) ProtoMessage() {}

func (x *AttachmentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_models_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentMeta.ProtoReflect.Descriptor instead.
func (*AttachmentMeta) Descriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{3}
}

func (x *AttachmentMeta) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AttachmentMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AttachmentMeta) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AttachmentMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AttachmentMeta) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *AttachmentMeta) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Keys contains vault encryption keys
type Keys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedAt          int64  `protobuf:"varint,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                             // UpdatedAt is a timestamp of keys update
	MasterKeyEncrypted []byte `protobuf:"bytes,2,opt,name=master_key_encrypted,json=masterKeyEncrypted,proto3" json:"master_key_encrypted,omitempty"` // MasterKeyEncrypted is a master key encrypted with a user master password and salt
	Salt               []byte `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`                                                         // Salt is a salt used to encrypt master key
}

func (x *Keys) Reset() {
	*x = Keys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_models_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_models_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{4}
}

func (x *Keys) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Keys) GetMasterKeyEncrypted() []byte {
	if x != nil {
		return x.MasterKeyEncrypted
	}
	return nil
}

func (x *Keys) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

// SyncServer is a configuration for a sync server
type SyncServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url          string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                          // URL is a URL of a sync server
	Username     string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                                // Username is a username for a sync server
	RefreshToken []byte `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`    // RefreshToken is a refresh token for a sync server
	LastSyncedAt int64  `protobuf:"varint,4,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"` // LastSyncedAt is a timestamp of last sync with this sync server
}

func (x *SyncServer) Reset() {
	*x = SyncServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_client_models_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncServer) ProtoMessage() {}

func (x *SyncServer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_client_models_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncServer.ProtoReflect.Descriptor instead.
func (*SyncServer) Descriptor() ([]byte, []int) {
	return file_internal_client_models_models_proto_rawDescGZIP(), []int{5}
}

func (x *SyncServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SyncServer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SyncServer) GetRefreshToken() []byte {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *SyncServer) GetLastSyncedAt() int64 {
	if x != nil {
		return x.LastSyncedAt
	}
	return 0
}

var File_internal_client_models_models_proto protoreflect.FileDescriptor

var file_internal_client_models_models_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0xd0, 0x01,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x24,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x31, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x22, 0x70, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x6b, 0x0a, 0x04, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x5f,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x12, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x41, 0x74, 0x2a,
	0xbe, 0x01, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x43, 0x55, 0x52, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x41, 0x4e, 0x4b, 0x5f, 0x43, 0x41, 0x52,
	0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x10,
	0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45, 0x43, 0x55, 0x52, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x45,
	0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45, 0x43, 0x55, 0x52, 0x45, 0x5f, 0x46, 0x49, 0x4c,
	0x45, 0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x43, 0x52,
	0x45, 0x44, 0x53, 0x10, 0x08, 0x12, 0x13, 0x0a, 0x0f, 0x57, 0x49, 0x52, 0x45, 0x4c, 0x45, 0x53,
	0x53, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x10, 0x09, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x4f,
	0x46, 0x54, 0x57, 0x41, 0x52, 0x45, 0x5f, 0x4c, 0x49, 0x43, 0x45, 0x4e, 0x53, 0x45, 0x10, 0x0a,
	0x2a, 0x7a, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x43, 0x52, 0x45,
	0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x54, 0x45, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x55, 0x52, 0x4c, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10,
	0x04, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10,
	0x42, 0x41, 0x4e, 0x4b, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52,
	0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x45, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a,
	0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x5f, 0x59, 0x45, 0x41, 0x52, 0x10, 0x08, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_client_models_models_proto_rawDescOnce sync.Once
	file_internal_client_models_models_proto_rawDescData = file_internal_client_models_models_proto_rawDesc
)

func file_internal_client_models_models_proto_rawDescGZIP() []byte {
	file_internal_client_models_models_proto_rawDescOnce.Do(func() {
		file_internal_client_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_client_models_models_proto_rawDescData)
	})
	return file_internal_client_models_models_proto_rawDescData
}

var file_internal_client_models_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_client_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_client_models_models_proto_goTypes = []interface{}{
	(ItemType)(0),          // 0: models.ItemType
	(FieldType)(0),         // 1: models.FieldType
	(*ItemMeta)(nil),       // 2: models.ItemMeta
	(*ItemData)(nil),       // 3: models.ItemData
	(*Field)(nil),          // 4: models.Field
	(*AttachmentMeta)(nil), // 5: models.AttachmentMeta
	(*Keys)(nil),           // 6: models.Keys
	(*SyncServer)(nil),     // 7: models.SyncServer
}
var file_internal_client_models_models_proto_depIdxs = []int32{
	0, // 0: models.ItemMeta.type:type_name -> models.ItemType
	4, // 1: models.ItemData.fields:type_name -> models.Field
	1, // 2: models.Field.type:type_name -> models.FieldType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_client_models_models_proto_init() }
func file_internal_client_models_models_proto_init() {
	if File_internal_client_models_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_client_models_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_client_models_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_client_models_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_client_models_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachmentMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_client_models_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_client_models_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_client_models_models_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_client_models_models_proto_goTypes,
		DependencyIndexes: file_internal_client_models_models_proto_depIdxs,
		EnumInfos:         file_internal_client_models_models_proto_enumTypes,
		MessageInfos:      file_internal_client_models_models_proto_msgTypes,
	}.Build()
	File_internal_client_models_models_proto = out.File
	file_internal_client_models_models_proto_rawDesc = nil
	file_internal_client_models_models_proto_goTypes = nil
	file_internal_client_models_models_proto_depIdxs = nil
}
